### PR TITLE
Replace placeholder with '...'

### LINKED ISSUE #138: ContributionsWrite - does not update placeholder data for "Content" after language selection
See Placeholder "Write something amazing ..." in Content-field

The language was selected from "english" to "german"

image

### PR DESCRIPTION
**Pull request by roschaefer**
Quill editor does not seem to receive updates from Vuejs components. The
cleaner solution here in my opinion is to simply remove the placeholder.
The placeholder for Candos was not visible either. You can check it by
clicking on the Cando button.

close #138

### CODE REVIEW

**Comment by visualjerk** [comment]
We did not handle the editor options properly in order for them to be reactive. This is fixed by:

- Using a computed property instead of a data property to provide the editor options
- Rerendering the editor element

**Comment by roschaefer** [comment]
@visualjerk Yeah, I tried to do that but didn't know how to do it the Vue way. So the trick here is to rerender the entire component with `v-if`?

I still can't see the translation for CanDos.

**Comment by visualjerk** [comment]
@roschaefer Exactly, as far as I see, a rerender of the entire editor component is the only solution that lets you pass in different editor options.

In my local environment the translations work for the CanDos Editor. Can you give me the exact steps leading to the issue, as well as the browser you are using?

**Comment by roschaefer** [comment]
```
$ firefox --version
Mozilla Firefox 61.0.1
```
```
robert@e480 ~/D/h/api> pwd
/home/robert/Development/human-connection/api
robert@e480 ~/D/h/api> git show --oneline
aca6e75 (HEAD -> develop, origin/develop, origin/HEAD) Merge pull request #111 from Human-Connection/dependabot/npm_and_yarn/nodemon-1.18.1
robert@e480 ~/D/h/api> cd ../webapp/
robert@e480 ~/D/h/webapp> git show --oneline
108770c (HEAD -> develop, origin/develop) Merge pull request #195 from Human-Connection/dependabot/npm_and_yarn/babel-eslint-8.2.5
```

simplescreenrecorder-2018-07-14_14 39 51

**Comment by roschaefer** [comment]
Ok, stupid me. :man_facepalming: so, at least I was expecting some change in the already visible input fields. Maybe it would be helpful to have some visual hint. How is the input for "Why is this Can Do useful?" different from the input  "Content"?

**Comment by visualjerk** [comment]
The difference is the place these texts were intended to go in the detail view of the canDo.

To be honest, the original design was changed quite a bit and the difference seems a little bit to subtle right now. Maybe we should completely get rid of these additional fields (reasonTitle and reason). @appinteractive What do you think about this topic?

**Comment by appinteractive** [comment]
>The difference is the place these texts were intended to go in the detail view of the canDo. ...

@visualjerk we should take a look if it makes sense and how it's used. I think anyway not everyone is using it. 

More fields means always more complexity. Maybe an template like with the github issue might be a way to guide the user a bit. @visualjerk what do you think?

**Pull request merged**
