### PR TITLE
add confirmation to leave the page when composing a comment

### PR DESCRIPTION
**Pull request by ionphractal**
This PR addresses close https://github.com/Human-Connection/WebApp/issues/234, adding a confirmation whenever the user tries to leave the page while composing a comment. It prevents losing drafts by mistake (e.g. accidentally clicking on a user name / mention when trying to quote the text).
There are two implementation steps
- open a vuejs dialog when clicking on any link staying inside the WebApp's domain (using vuejs beforeRouteLeave); the dialog is themed and i18n'ed
- listen to 'onbeforeunload' window event and show a browser based alert as required by html5 spec

Edit: I went for the fastest implementation of the referenced feature request because it has most impact relative to the effort.

### CODE REVIEW

**Comment by ionphractal** [comment]
@appinteractive You mean onbeforeunload? Why? Without this, you may still accidentally close the browser window or browse a new address and your draft would be lost. Do you have a better way to prevent it?

**Comment by appinteractive** [comment]
I just meant that you need to remove the event listener before destroying the component. Other wise you create a memory leak while piling up all those event listeners that gets created happily every time you visit a new contribution page.

**Comment by appinteractive** [comment]
`window.addEventListener('beforeunload', (e) => {
+ ` that one here needs a removeEventListener counterpart.

**Comment by ionphractal** [comment]
@appinteractive Sorry, misunderstood you. Yes, will do, thanks for the hint.

**Comment by ionphractal** [comment]
> yarn global v1.3.2
[1/4] Resolving packages...
error Received malformed response from registry for undefined. The registry may be down.

@appinteractive This can happen but was not caused by my commit... would you trigger the pipeline again, please?

**Pull request merged**
