### PR TITLE
Mobile navigation

### PR DESCRIPTION
**Pull request by visualjerk**

### CODE REVIEW

**Comment by HC-Team** [comment]
The topic icons are a bit streched, the emotion ones are perfecly round.

grafik

**Comment by HC-Team** [comment]
only the mobile search is working, the desktop one not! The desktop one reloads the whole page and then stops working completly

**Comment by visualjerk** [comment]
Good catch! The icons were fine in Chrome, but stretched in Firefox. For some weird reason the fixed flex value '0 0 2.25em' did not work here, so we needed to provide a max-width and min-width. The desktop search is fixed as well.

**Comment by appinteractive** [comment]
Well done

**Pull request merged**
