### PR TITLE
Application Logo in the top left corner gets default click behaviour

### LINKED ISSUE #267: HC Logo is not a link
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I middle-click on the HC logo on the top left "back to home" and no tab opens.

**Describe the solution you'd like**
The home logo should be a link.

**Describe alternatives you've considered**
Nah, this is a best practice in web development. Make the link a real anchor `<a .. >`.

**Additional context**
screenshot 5

### PR DESCRIPTION
**Pull request by brickmaker17**
fix #267

### CODE REVIEW

**Comment by roschaefer** [comment]
@brickmaker17 that's great! Thank you so much :bowing_man:   Why so many changes? Is it your editor?

**Comment by brickmaker17** [comment]
> @brickmaker17 that's great! Thank you so much 🙇 Why so many changes? Is it your editor?

ya my editor did all those changes. Do you want me to redo it ?

**Comment by appinteractive** [comment]
Thanks for your commit! And yeah could you please redo the formatting part? 

Also will that change reload the whole page instead of using the Vue Router. 
Could you add:

```
If (!e.metaKey && !e.ctrlKey) {
  e.preventDefault()
  // and move the Router part here 
}

**Comment by roschaefer** [comment]
@brickmaker17 ping :slightly_smiling_face: what's the status of this?

Pro Tip: I will add the keyword `fix 267` to the description of your PR request. When sb. merges this PR, this issue will automatically be closed. See Github documentation: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by brickmaker17** [comment]
> @brickmaker17 ping 🙂 what's the status of this?
> 
> Pro Tip: I will add the keyword `fix 267` to the description of your PR request. When sb. merges this PR, this issue will automatically be closed. See Github documentation: https://help.github.com/articles/closing-issues-using-keywords/

I will work on it this weekend.

**Comment by roschaefer** [comment]
@brickmaker17 I updated the PR with a smaller fix.

@appinteractive could you review and merge if possible?

**Comment by roschaefer** [comment]
OK, @appinteractive is unavailable today, so I'll merge!

**Comment by roschaefer** [comment]
@brickmaker17 thank you so much!

**Comment by roschaefer** [comment]
@brickmaker17 and I mentioned you in our video blog (in German): https://youtu.be/L_F0CKpecPU

**Pull request merged**
