### PR TITLE
Metascraper

### PR DESCRIPTION
**Pull request by visualjerk**
Add url-embeds to contribution editor

### CODE REVIEW

**Comment by appinteractive** [comment]
You still need to encode the urls before sending them to the embeds api!
grafik

**Comment by appinteractive** [comment]
Issue with links in between sentences. 
kapture 2018-04-08 at 15 49 22

**Comment by visualjerk** [comment]
These issues should be fixed with the latest commit.

**Comment by appinteractive** [comment]
somehow the link or the style gets destroyed after or on save. 
Also the linebreaks after and before the embed get killed.

kapture 2018-04-09 at 17 11 41

**Comment by visualjerk** [comment]
The style issue is fixed by the latest commit to the API.

**Pull request merged**
